debug: true
bungeecord: true
language: de
mysql:
  user: ####
  password: ####
  database: ####
  url: ####
  parameters: ""
  tables:
    player: Guilds_Player
    guilds: Guilds_Guilds
    ranks: Guilds_Ranks
    invites: Guilds_Invites
    blackboard: Guilds_Blackboard
    alliance: Guilds_Alliances
    allianceInvites: Guilds_AllianceInvites
    moneyLog: Guilds_MoneyLog
guilds:
  blackboard:
    limit: 6
  lists:
    pageSize: 10
  guildNameLength: 30
  guildTagLength: 4
  prefixLength: 25
  crossServerTeleport: false
bonus:
  cheaperEnchantment: true
  moreFurnaceExp: false
  doubleCrafting: false
  specialDrop: true
specialDrops:
  COAL: 1.0
  IRON_INGOT: 0.5
  GOLD_INGOT: 0.2
  EMERALD: 1.0
  DIAMOND: 1.0
  REDSTONE: 1.0
  QUARTZ: 1.0
  LAPIS_LAZULI: 1.0
upgrade:
  requireMoney: true
  requirePlayers: true
  requireExp: true
  requireMaterial: true
level:
  '1':
    name: 'Bruderschaft'
    limit: 10
    bankLimit: 5000
    enchantmentCost: 0.97
    doubleCraftProbability: 0.01
    specialDropChance: 0.01
    furnaceExpGainRatio: 1.05
    upgradeCost: 2500
    upgradePlayers: 0
    upgradeExpCost: 0
    upgradeMaterials:
      # the list must not be emtpy, ignore this
      DIRT: 1
  '2':
    name: 'Gruppe'
    limit: 15
    bankLimit: 7500
    enchantmentCost: 0.95
    doubleCraftProbability: 0.02
    specialDropChance: 0.02
    furnaceExpGainRatio: 1.1
    upgradeCost: 5000
    upgradePlayers: 5
    upgradeExpCost: 3500
    upgradeMaterials:
      DIAMOND: 16
      MOSSY_COBBLESTONE: 64
      OAK_SAPLING: 64
      GLOWSTONE: 64
  '3':
    name: 'Mannschaft'
    limit: 20
    bankLimit: 10000
    enchantmentCost: 0.93
    doubleCraftProbability: 0.03
    specialDropChance: 0.03
    furnaceExpGainRatio: 1.15
    upgradeCost: 7500
    upgradePlayers: 6
    upgradeExpCost: 10000
    upgradeMaterials:
      DIAMOND: 24
      ANVIL: 1
      IRON_SWORD: 3
      GOLDEN_SWORD: 2
      DIAMOND_SWORD: 1
  '4':
    name: 'Horde'
    limit: 25
    bankLimit: 15000
    enchantmentCost: 0.9
    doubleCraftProbability: 0.04
    specialDropChance: 0.04
    furnaceExpGainRatio: 1.2
    upgradeCost: 10000
    upgradePlayers: 7
    upgradeExpCost: 15000
    upgradeMaterials:
      DIAMOND: 32
      SADDLE: 3
      LEAD: 32
      LEATHER: 64
      CARROT: 64
  '5':
    name: 'Schar'
    limit: 30
    bankLimit: 20000
    enchantmentCost: 0.87
    doubleCraftProbability: 0.05
    specialDropChance: 0.05
    furnaceExpGainRatio: 1.25
    upgradeCost: 15000
    upgradePlayers: 8
    upgradeExpCost: 30000
    upgradeMaterials:
      GOLD_INGOT: 64
      IRON_INGOT: 64
      IRON_SWORD: 4
      IRON_CHESTPLATE: 4
  '6':
    name: 'Front'
    limit: 35
    bankLimit: 30000
    enchantmentCost: 0.83
    doubleCraftProbability: 0.06
    specialDropChance: 0.06
    furnaceExpGainRatio: 1.3
    upgradeCost: 20000
    upgradePlayers: 9
    upgradeExpCost: 40000
    upgradeMaterials:
      SHIELD: 12
      IRON_INGOT: 64
      BREAD: 64
      POTATO: 64
  '7':
    name: 'Bund'
    limit: 40
    bankLimit: 40000
    enchantmentCost: 0.80
    doubleCraftProbability: 0.07
    specialDropChance: 0.07
    furnaceExpGainRatio: 1.35
    upgradeCost: 30000
    upgradePlayers: 10
    upgradeExpCost: 50000
    upgradeMaterials:
      POPPY: 16
      DIAMOND: 32
      GOLD_INGOT: 64
      ANVIL: 1
      WRITABLE_BOOK: 1
  '8':
    name: 'Liga'
    limit: 45
    bankLimit: 50000
    enchantmentCost: 0.77
    doubleCraftProbability: 0.08
    specialDropChance: 0.08
    furnaceExpGainRatio: 1.4
    upgradeCost: 40000
    upgradePlayers: 11
    upgradeExpCost: 75000
    upgradeMaterials:
      WRITABLE_BOOK: 3
      MAP: 64
      IRON_SWORD: 16
      DIAMOND: 64
  '9':
    name: 'Legion'
    limit: 50
    bankLimit: 60000
    enchantmentCost: 0.73
    doubleCraftProbability: 0.09
    specialDropChance: 0.09
    furnaceExpGainRatio: 1.45
    upgradeCost: 50000
    upgradePlayers: 12
    upgradeExpCost: 100000
    upgradeMaterials:
      SHIELD: 16
      GOLDEN_SWORD: 16
      POPPY: 16
      BREAD: 64
      PUMPKIN_PIE: 64
      COOKED_MUTTON: 64
  '10':
    name: 'Armee'
    limit: 60
    bankLimit: 75000
    enchantmentCost: 0.70
    doubleCraftProbability: 0.1
    specialDropChance: 0.10
    furnaceExpGainRatio: 1.5
    upgradeCost: 60000
    upgradeExpCost: 125000
    upgradePlayers: 13
    upgradeMaterials:
      BEACON: 1
      DIAMOND_HELMET: 5
      DIAMOND_CHESTPLATE: 5
      DIAMOND_LEGGINGS: 5
      DIAMOND_BOOTS: 5
  '11':
    name: 'Heer'
    limit: 75
    bankLimit: 100000
    enchantmentCost: 0.67
    doubleCraftProbability: 0.11
    specialDropChance: 0.11
    furnaceExpGainRatio: 1.55
    upgradeCost: 75000
    upgradePlayers: 14
    upgradeExpCost: 150000
    upgradeMaterials:
      GOLDEN_APPLE: 64
      GOLD_BLOCK: 64
      CLOCK: 4
      GOLDEN_SWORD: 16
  '12':
    name: 'Streitmacht'
    limit: 100
    bankLimit: -1
    enchantmentCost: 0.63
    doubleCraftProbability: 0.12
    specialDropChance: 0.12
    furnaceExpGainRatio: 1.6
    upgradeCost: 100000
    upgradePlayers: 15
    upgradeExpCost: 200000
    upgradeMaterials:
      DRAGON_EGG: 1
      BANNER: 1
      INK_SAC: 64
      IRON_HORSE_ARMOR: 1
      GOLD_HORSE_ARMOR: 1
      DIAMOND_HORSE_ARMOR: 1

